#![allow(dead_code)]
#![cfg_attr(rustfmt, rustfmt_skip)]

mod utils;

mod p5_longest_palindromic_substring;
mod p6_zigzag_conversion;
mod p7_reverse_integer;
mod p8_string_to_integer_atoi;
mod p9_palindrome_number;
mod p11_container_with_most_water;
mod p14_longest_common_prefix;
mod p15_3sum;
mod p16_3sum_closest;
mod p17_letter_combinations_of_a_phone_number;
mod p18_4sum;
mod p19_remove_nth_node_from_end_of_list;
mod p20_valid_parentheses;
mod p21_merge_two_sorted_lists;
mod p22_generate_parentheses;
mod p24_swap_nodes_in_pairs;
mod p26_remove_duplicates_from_sorted_array;
mod p27_remove_element;
mod p28_find_the_index_of_the_first_occurrence_in_a_string;
mod p29_divide_two_integers;
// mod p30_substring_with_concatenation_of_all_words;
mod p31_next_permutation;
// mod p32_longest_valid_parentheses;
mod p33_search_in_rotated_sorted_array;
mod p34_find_first_and_last_position_of_element_in_sorted_array;
mod p35_search_insert_position;
mod p36_valid_sudoku;
// mod p37_sudoku_solver;
mod p38_count_and_say;
mod p39_combination_sum;
mod p40_combination_sum_ii;
mod p41_first_missing_positive;
mod p42_trapping_rain_water;
mod p43_multiply_strings;
// p44_wildcard_matching;
mod p45_jump_game_ii;
mod p46_permutations;
mod p47_permutations_ii;
mod p48_rotate_image;
mod p49_group_anagrams;
mod p50_powx_n;
// mod p51_n_queens;
// mod p52_n-queens_ii;
mod p53_maximum_subarray;
mod p54_spiral_matrix;
mod p55_jump_game;
mod p56_merge_intervals;
mod p57_insert_interval;
mod p58_length_of_last_word;
mod p59_piral_matrix_ii;
mod p60_permutation_sequence;
mod p61_rotate_list;
mod p62_unique_paths;
mod p63_unique_paths_ii;
mod p64_minimum_path_sum;
// mod p65_valid_number;
mod p66_plus_one;
mod p67_add_binary;
mod p68_text_justification;
mod p69_sqrtx;
mod p70_climbing_stairs;
mod p71_simplify_path;
mod p72_edit_distance;
mod p73_set_matrix_zeroes;
mod p74_search_a_2d_matrix;
mod p75_sort_colors;
// mod p76_minimum_window_substring;
mod p77_combinations;
mod p78_subsets;
mod p79_word_search;
mod p80_remove_duplicates_from_sorted_array_ii;
mod p81_search_in_rotated_sorted_array_ii;
mod p82_remove_duplicates_from_sorted_list_ii;
mod p83_remove_duplicates_from_sorted_list;
mod p84_largest_rectangle_in_histogram;
mod p85_maximal_rectangle;
mod p86_partition_list;
mod p87_scramble_string;
mod p88_merge_sorted_array;
mod p1742_maximum_number_of_balls_in_a_box;
